<?php defined('SYSPATH') OR die('No direct access allowed.'); ?>
<style>
ol.alpha {
    list-style-type: lower-alpha;
    padding-left: 50px;
    padding-bottom: 20px;
}

ol.num {
    list-style-type: decimal;
    padding-left: 50px;
    padding-bottom: 20px;
}

</style>

<h1><?= __('Swurve Terms of Service'); ?></h1>

<p>Swurve.com is an online community created for, and intended to be accessed exclusively by, ADULTS ONLY. Access or use of this website in any way by individuals under the age of 18 years old is strictly prohibited. </p>
<p> By registering an account with Swurve.com (referred to herein as the “Service” or “site”) you are expressly signifying you agree to the following terms and conditions and affirm you will abide by the acceptable use policies outlined in this Agreement (“the Agreement”). We encourage you completely read the following terms and conditions carefully as they form the Agreement between you (also referred to herein as “you”, “member” or “user”) and Swurve Media Corporation (referred to hereinafter as “swurve.com”, “we” or “us”) and you agree to be bound by these terms and conditions for as long as you continue to be a member. IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS OUTLINED IN THIS AGREEMENT YOU SHOULD NOT ACCESS THE SITE. </p>
<p> We reserve the right to modify the terms of the Agreement at any time. Any changes made will be considered effective immediately upon notice. Notice of changes to the Agreement will be posted on the site whenever significant updates are made. Your continued use of the Service after such notice signifies your acceptance of these changes. A link to the Agreement will always be made available to you through inclusion in the footer located on the bottom of the Service’s home page for your review at any time. </p>
<p> <strong>ELIGIBILITY</strong> </p>
<p> The Swurve.com website and Service is intended for use solely by adults only and membership is void where prohibited. </p>
<p> By registering an account with the Service you warrant that:</p>
<ol type="a" class="alpha">
  <li>you are of legal age (18 years of age or older)</li>
  <li>you have the right, authority and capacity to enter into this Agreement and abide by all terms and conditions outlined herein </li>
  <li>you have chosen to access the Service of your own free will in order to view, read, watch and / or hear the content available for your own personal enjoyment</li>
  <li>you shall not permit any unauthorized person(s) or individuals under the age of 18 to access the Service or view website content through your actions or omissions</li>
  <li>you have not notified any government agency, including the United States Postal Service, that you do not wish to receive sexually oriented material</li>
  <li>you shall not access the Service in any jurisdiction where doing so would be considered a violation of law, regulation, rule, ordinance, edict, or community standards.</li>
</ol>
<p><strong>REGISTRATION</strong> </p>
<p> To become a member of Swurve.com registration of a user account is required. By creating an account you agree that the information you provide about yourself (“user data”) is truthful, accurate, current and complete.  It is also your responsibility to update your user data to ensure its continued accuracy as long as you are an active participant in the Service. You acknowledge that should your user data be found to be false or inaccurate in any respect we reserve the right to terminate the account and suspend access to the site. </p>
<p> Upon registration we will require you provide sufficient information to affirm that you are at least 18 years of age. By registering an account you represent and warrant that you are at least 18 years old, the minimum age requirement to acquire membership and access the Service. We take precautionary measures to prevent, and will not knowingly permit, anyone under the age of 18 to access our Services, however, we cannot guarantee that each user is at least the required minimum age, nor do we accept responsibility or liability for any content, communication or other use or access of the Service by persons under the age of 18 in violation of the Agreement. </p>
<p> You hereby acknowledge and agree you understand that granting access to an age restricted community and the adult oriented content provided within made available by the Service and its affiliated content providers to a minor constitutes unauthorized accessing of the company’s computers and databases in violation of the Agreement and that such unauthorized access violates state, federal and foreign laws, including, without limitation, The Electronic Communications Privacy Act, 18 U.S.C. Â§ 2701-2710, The Computer Fraud and Abuse Act, 18 U.S.C. 1030 and The California Comprehensive Computer Data Access and Fraud Act, Cal. Penal Code 502 and constitutes trespass to chattels, and intentional copyright infringement(s) of the company's copyrights in the website and in content owned by the company, and/or other parties, that is displayed in, at or through the Service all of which are protected under the laws of the United States and other countries. You further acknowledge that you understand that any such unauthorized access of the Service and/or company content or our affiliated content providers' content on the company's computers could subject you to potential criminal prosecution and substantial civil liability of up to $150,000 per work infringed.</p>
<p><strong>USERNAME AND PASSWORD</strong> </p>
<p> During the registration process on Swurve.com you will be asked to create a username and password to access the Service.  Your username and password is intended for your sole personal use. It is your responsibility to maintain the confidentiality of your username and password and the security of your account. You agree not to share, transfer or resell your access to the Service to any third parties in any way. You are fully responsible for all activities that occur on the Service via use of your username and password, whether or not authorized by you. You agree to pay all charges accrued by use of your account on the Service. Simultaneous use of one account from multiple computers is prohibited. </p>
<p> We reserve the right to edit, refuse or revoke any username that impersonates another individual, contains racial slurs or otherwise vulgar or offensive language, is or may be illegal, makes reference to illegal activity, is or may be protected by trademark, copyright or other proprietary rights law, or has been designed to cause confusion, as we see fit at our sole discretion. </p>
<p> You may change your password at any time from the “Account Settings” page which can be accessed from your Control Panel on the site. If you feel your password has been compromised or other unauthorized use of your account has occurred it is your responsibility to notify Swurve.com of the breach immediately by emailing <a href="mailto:support@swurve.com">support@swurve.com</a>.</p>
<p><strong>USER SUBMITTED CONTENT</strong> </p>
<p> You are solely responsible for the content you submit, publish, display on Swurve.com or transmit to other users through the Service. You agree to not publish any content that could be construed as:</p>
<ol type="a" class="alpha">
  <li>libelous, defamatory or slanderous </li>
  <li>containing derogatory remarks against any ethnic, racial or religious group </li>
  <li>promoting racism, bigotry, hatred, or physical harm </li>
  <li>depicting, describing or soliciting individuals under 18 years of age in a sexual manner</li>
  <li>depicting, describing or soliciting illegal activity such as drug use</li>
  <li>advocating harassment of other persons or members of the community</li>
  <li>soliciting, advertising, or otherwise promoting any commercial service, product or other venture</li>
  <li>violating existing copyright held by a third party</li>
</ol>
<p>Swurve.com claims immunity from liability to the fullest extent under the law as provided under section 230 of the Communications Decency Act for content submitted by users and third parties and nothing contained within the Agreement shall waive, remove or usurp such immunity. </p>
<p> By submitting content to the site you represent and warrant that you are the author of the content you are submitting, including without limitation text and digital media including photographs and videos, and that you have the right to grant Swurve Media Corporation and its licensees, affiliates and successors perpetual, irrevocable, royalty-free right and global license to use, reproduce, modify, display and distribute or incorporate into other works such content, and grant and authorize sublicenses of the foregoing. </p>
<p> Swurve.com reserves the right to delete or edit any content it feels violates the terms and conditions or otherwise is counter-productive to fostering a positive a positive online community environment. The Service also strictly prohibits the publication for display of personal information such as last names, phone numbers, outside email or physical addresses. This is for our members’ personal security and such information should only be shared privately with the Service through registration, when providing billing details to acquire membership, or in private member to member communications that are not available for view by the community at large.</p>
<p><strong>CODE OF CONDUCT</strong> </p>
<p> As a registered user of Swurve.com you agree to use the Service in accordance with the following code of conduct. Failure to abide by the guidelines outlined in the Agreement may result in restricted access and termination of your account. </p>
<p> You agree to not post on the Service or transmit to its users or employees any content that is intended to be defamatory, abusive, libelous, slanderous, obscene, profane, racist, offensive, threatening, harassing, illegal or is otherwise designed to infringe on another party’s rights. </p>
<p> You agree that in your use of the Service you will:</p>
<ol class="num">
  <li>use the Service in a manner consistent with any and all applicable laws and regulations;</li>
  <li>provide information that is truthful, honest and accurate;</li>
  <li>keep all information provided to you by other users through the Service private and confidential and will not share such information to any third party without permission;</li>
  <li>not impersonate any person or entity;</li>
  <li>not “stalk”, make physical or personal threats, or use the Service to otherwise harass any person(s);</li>
  <li>not create multiple accounts or personalities with the intention  to confuse, mislead, or otherwise interfere with other users; </li>
  <li>not post any content to the Service which violates, plagiarizes or infringes on the rights of any third party;</li>
  <li>not distribute, promote or otherwise publish any material containing solicitation for funds, advertising or solicitation for goods or services;</li>
  <li>not promote yourself as it relates to your participation in any other website or service nor redirect users of Swurve.com to any other service or web entity</li>
  <li>not use the Service to distribute unsolicited commercial email (“SPAM”), chain letters or other non-relevant mass mail messaging to other users;</li>
  <li>not perform any action intended to circumvent the navigational structure or security of the Service, including, without limitation, forged routing or email address  information, IP spoofing, or manipulation of cookies;</li>
  <li>not modify, adapt, sublicense, sell, reverse engineer, manipulate or otherwise disassemble any portion of the website or any of the proprietary software of the Service or encourage others to do so;</li>
  <li>not perform any action intended to interfere with or damage the Service, including, without limitation, the use of viruses, Trojan horses, spyware, malicious code, or denial of service attacks; and </li>
  <li>not assist any third party in performing any of the actions listed above</li>
</ol>
<p>You are solely responsible for your communications and interactions with other users of the Service. The company reserves the right, but has no obligation, to monitor communications between members of the Service. Monitoring user communications is done primarily in the interest of resolving user disputes and investigating claims of fraud or harassment. We will not modify or otherwise edit communications between users other than the removal of text that violates the user code of conduct. </p>
<p> As a user of Swurve.com you agree and understand that the user to user interaction on the Service is not a product that cannot be controlled, forced or guaranteed and therefore shall be viewed as being of entertainment value only and you will not hold the company liable for any negative consequences that may arise as a direct or indirect result from such interaction. You understand that the company, its shareholders, employees and agents make no warranties and have not verified any of the user provided content and information found on the Service. If you feel another user of the Service is in violation of these rules, please notify us by sending an email containing the member’s user name and a description of the violation to <a href="mailto:support@swurve.com">support@swurve.com</a> .</p>
<p><strong>ACKNOWLEDGEMENT OF SEXUALLY ORIENTED CONTENT</strong> </p>
<p> You hereby acknowledge that content made available at, in, through and in association with, Swurve.com and the Service include explicit textual, visual, and / or audio depictions of nudity and sexual situations. By accessing the site you acknowledge that you are not offended by such materials and that that by agreeing to the terms and conditions outlined herein you are warranting to the company and affiliated content providers that you are intentionally and knowingly seeking to access such materials for your own personal viewing.</p>
<p><strong>MEMBERSHIP</strong> </p>
<p> Swurve.com offers different membership levels (or tiers) which correspond to various levels of access, feature usage and membership privileges available to you through the Service. You do not have to be a paying member to be a user of the Service and hold an active account with Swurve.com, but paying (or premium) members are provided with access to additional features that are not available to non-paying users. The highest membership tier has the greatest level of site access, feature usage and has the greatest number of membership privileges available on the Site. We reserve the right to add or remove features and membership privileges, as well as expand or restrict site access to any membership tier at any time at our sole discretion to meet the changing needs of our community. </p>
<p> To upgrade your member status you may choose one of our membership packages and corresponding tiers. Membership is payable via credit card, check or money order as outlined on the payment pages of the Site.  If you select a membership option that include recurring billing you authorize Swurve.com and our payment processor to charge the credit card you have submitted for the ongoing cost of access to the Service. Payment for the appropriate services will be deducted automatically using the account information you have provided and the membership renewed automatically for a term equal to the original term you selected on an ongoing basis until the account has been canceled. </p>
<p> All membership fees paid to Swurve.com are non-refundable and membership to the Service, paid or unpaid, is non-transferrable. Paid membership to Swurve.com may only be applied to one account. In the event a user has two accounts on the Service they may either upgrade both accounts or wait until their initial paid account expires. Accounts cannot be merged. </p>
<p> Certain features on Swurve.com are provided on a “Pay-per-Play” basis. Access to these features is based on a credit system. Credits can be purchased through the Site separately from and in addition to membership. Credits can only be utilized by users with active premium memberships. If your account has been cancelled any credit balance you have remaining after your membership’s expiration will stay until you choose to reactivate your subscription. If your account has been terminated by the service any credit balance that may remain will be forfeited. Credits cannot be “cashed out” or exchanged for cash back or refund. All credit purchases are non-refundable. </p>
<p> We reserve the right to change package pricing as well as the payment methods accepted by the Service at any time at our sole discretion. These changes may be made with no notice and will be effective once the payment pages have been updated to reflect the new pricing. </p>
<p> The feature access for unpaid members may be expanded or restricted as we see fit to maintain healthy levels of community activity. As membership tiers and package pricing evolves some members may be privy to be grandfathered in at lower rates than those currently available through the payment pages. Additionally, from time to time to ensure an active community and a balanced gender ratio certain aspects of the population may be incentivized. Incentives include, but are not limited to, free upgrades to premium membership tiers and complementary access to premium features of the Service. We will never offer incentives to communicate with users in a specific manor, to meet members in person or otherwise engage in other forms of offline communication outside the Service. User to user interaction is at the discretion of the users themselves. </p>
<p><strong>CANCELLATION AND FORFEITURE</strong> </p>
<p> Membership to Swurve.com may be cancelled at your request. Cancellation can be made by submitting your request to customer service at <a href="mailto:support@swurve.com">support@swurve.com</a> , calling our toll free number between the hours of 9:00 AM and 9:00 PM Eastern Standard Time, or in writing by postal mail to Swurve Media Corp, 1497 Main St, Suite 331, Dunedin, FL 34698. When submitting your request by email please include the username of the account you wish to cancel and be sure to send the request from the email address registered in connection with the account. Requests to cancel recurring memberships must be received by customer service at least 3 business days prior to your next scheduled billing date. Cancellation requests received with less than 3 business days processing time may not be cancelled prior to your next scheduled billing and these fees will not be refundable. </p>
<p> Once your cancellation has been processed you will continue to have premium access to the Service for the remainder of the time you paid for. If you wish to forfeit the remainder of your time your access can be discontinued and your account removed from the system prematurely but your membership fees will remain non-refundable. To forfeit your account please contact customer service at <a href="mailto:support@swurve.com">support@swurve.com</a> with your user name, your forfeit request and a written confirmation that you understand these terms.</p>
<p><strong>TERMINATION</strong> </p>
<p> You acknowledge and understand that Swurve.com may terminate your access to the Service at our sole discretion for any reason, including, but without limitation, your breach of the terms outlined in the Agreement. You agree that termination of your access to the Service may occur without prior notice or written warning and acknowledge and agree that we may immediately delete and deactivate any of your accounts and related content files upon termination as well as bar any further access to Swurve.com and the Service. Terminated accounts are not entitled to refunds, transfers, or credit for any unused portion of membership remaining at the time of termination. Termination of your account does not terminate the Agreement.</p>
<p><strong>INTELLECTUAL PROPERTY CLAIMS</strong> </p>
<p> We at Swurve.com respect the intellectual property rights of others and we encourage our users do the same. We fully comply with the Digital Millennium Copyright Act (“DCMA”) and follow notification and removal provisions as part of our compliance so we may benefit from the safe harbors which offer us immunity from liability to the fullest extent provided by the law. Intentional copyright infringement by any user of the Service may result in the loss of membership privileges and termination of the account. </p>
<p> If you believe that content submitted to our Service violates your intellectual property rights, or constitutes copyright infringement, please provide the following information:</p>
<ol class="num">
  <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest;</li>
  <li>a description of the copyrighted work or other intellectual property that you claim has been infringed;</li>
  <li>a description of where the material that you claim is infringing is located on the Multicast site or system, with enough detail so that we may find it;</li>
  <li>your address, telephone number, and email address where you can be reached</li>
  <li>a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or intellectual property owner, its agent, or the law;</li>
  <li>a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner's behalf.</li>
</ol>
<p>This notice can be sent to our offices electronically by emailing the required information and supporting documents to <a href="mailto:webmaster@swurve.com">webmaster@swurve.com</a> or can be physically mailed to the following address: Swurve Media Corp, ATTN: Copyright Agent, 1497 Main St, Suite 331, Dunedin, FL 34698 </p>
<p> Upon receipt of a Notice for Claims of Intellectual Property Violations the company will take the following action: </p>
<p> Promptly remove or temporarily disable the material in question </p>
<p> Notify the user responsible for uploading the material in question that a Notice for Claims of Intellectual Property Violations has been received and that the alleged infringing material has been removed; and </p>
<p> Provide the user with a Counter Notification Form and information outlining the steps required if they wish to respond and dispute the content removal by showing ownership of the content in question.</p>
<p><strong>COUNTER CLAIMS TO INTELLECTUAL PROPERTY NOTIFICATIONS</strong> </p>
<p> If you are a user of Swurve.com and have received a notification from us regarding the take down of disputed content it is because a proper Notice for Claims of Intellectual Property Violation has been received meeting the criteria outlined in the section above claiming that content submitted by you is infringing on the intellectual property rights of another party. </p>
<p> If you believe we have removed this content mistakenly and you are confident you are the author of the disputed content you can send a counter-notice as described below to our offices containing the following information:</p>
<ol class="num">
  <li>your electronic or physical signature as a subscriber to or user of our Services;</li>
  <li>a description of the material that has been removed or to which access has been disabled;</li>
  <li>a description of where on our system the material appeared before it was removed or access to it was disabled;</li>
  <li>your address, telephone number, and email address;</li>
  <li>a statement by you, made under penalty of perjury, that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; and</li>
  <li>a statement that you consent to the jurisdiction of Federal District Court for the judicial district in which your address is located, or if your address is outside of the United States, for any judicial district in which Multicast may be found, and that you will accept service of process from the person who provided the original notification claiming infringement or from an agent of such person.</li>
</ol>
<p>If we receive a counter-notice as described above, and in accordance with U.S. copyright law, upon receipt of a counter notification described above we will promptly provide a copy of the counter-notice to the party who provided the original notification claiming infringement and we will inform such party that we will replace the removed material or cease disabling access to it in ten (10) business days. Thereafter, and again, as specified by U.S. copyright law, we will replace the removed material and cease disabling access to it not less than ten (10), nor more than fourteen (14), business days following receipt of the counter notice, unless Swurve's Copyright Agent first receives notice from the person who provided the original notification claiming infringement that such person has filed an action seeking a court order to restrain the user (the original poster of the content in question to the Service) from engaging in infringing activity relating to the material on the Swurve.com website.</p>
<p><strong>NON-COMMERCIAL USE   </strong> </p>
<p> Swurve.com is intended for personal use only and use of the Service in conjunction with any commercial venture is strictly prohibited. Companies or organizations wishing to advertise on Swurve.com or have interest in forming a business relationship with us may contact <a href="mailto:webmaster@swurve.com">webmaster@swurve.com</a> . Illegal and / or unauthorized use of the Service by companies, organizations or individuals for personal or commercial gains will be investigated and appropriate legal action will be taken, including without limitation civil, criminal, and injunctive redress. </p>
<p><strong>PROPRIETARY RIGHTS</strong> </p>
<p> All content and materials available on Swurve.com are the sole property of us and are protected by our rights and /or the rights of our licensors including but not limited to trademarks, copyrights, service marks, publicity, patents, trade secrets, and proprietary software. Except for that information which is public domain or which you have been given express permission you will not duplicate, modify, publish, transmit, distribute, perform, display, sell, license or rent any such proprietary information. </p>
<p> You agree to not systematically retrieve data, content, or other materials from the Service with intention to create or compile a collection, compilation, database, directory or the like whether by manual methods, employing the use of scripted programs or by any other means. You agree not to use our company name, domain name, or any of our other trademarks as metadata for other websites. You agree not to hot link, display in a frame or otherwise link any content originally hosted on our Service through any outside web entity. However, you are welcome to establish ordinary direct links to the home page of our site without our written consent. All other linking or promotion should go through our affiliate program located at <a href="http://affiliates.swurve.com">http://affiliates.swurve.com</a> .</p>
<p> <strong>PRIVACY POLICY</strong> </p>
<p> By registering an account on Swurve.com you also submit and agree to our Privacy Policy. As fully detailed in our <?= HTML::anchor('privacy', 'Privacy Privacy'); ?> page, your personal information will not be resold to any third party. You acknowledge and understand that we cannot make any warranties that ensure the security or privacy of information you provide through the Internet, email or other communications and you release us from any and all liability in should a breach of our security of such information and/or messages take place; we are not responsible for nor can we control the use of any information by anyone which you provide to any other parties through the Service and you should exercise caution in deciding what personal information you select to share with other users; we cannot assume responsibility for the content of any personal communication sent by any user on the Service and you agree to hold us harmless for the content of any communications you receive from other users.</p>
<p><strong>INTERVIEWS, ARTICLES AND ADVICE COLOMNS</strong> </p>
<p> At times the Service provided by Swurve.com may include live chat, article and interview content from guest writers, staff members and celebrities, experts and advice columnists. This content may include opinions, personal experiences and observations on the subject of lifestyle, health, relationship and human sexuality. Any oral or written opinions, advice, statements, offers or other information or content made available through the Service are those of their respective user-author and not necessarily those of the company and should be viewed as being for entertainment purposes only and not necessarily be relied upon. These statements are not intended to constitute counseling of any kind. This information is not intended to take the place of meeting with a therapist or physician and users of the Service seeking a professional help or a medical opinion are strongly encouraged to speak with a licensed therapist or qualified medical professional.</p>
<p><strong>COOPERATION WITH LAW ENFORCEMENT AGENCIES        </strong> </p>
<p> Swurve.com reserves the right to fully comply with any and all law enforcement agencies and court orders requesting or directing the company, its affiliates and content providers to disclose information regarding any individual who is using or has used the Service or has obtained content available or in association with the website. By accepting this Agreement and through continued access to the website and use of the Service you agree to waive and hold harmless the company, its affiliates and content providers from any and all claims resulting from any and all actions that result from cooperation with any law enforcement agency or legal authority’s investigations.</p>
<p><strong>DISCLAIMER OF WARRANTY</strong> </p>
<p> YOU ACKNOWLEDGE AND UNDERSTAND THAT IN USING OUR SERVICE PROVIDED THROUGH THE SWURVE.COM WEBSITE YOU DO SO AT YOUR OWN RISK. THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS AND THE COMPANY GRANTS NO WARRANTIES OF ANY KIND, EXPRESS, IMPLIED OR STATUTORY IN REGARDS TO THE SERVICE OR THE WEBSITE. SWURVE.COM EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES, INCLUDING, BUT WITHOUT LIMITATION, WARRANTIES OF AVAILABILITY, ACCURACY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR NON-INFRINGEMENT. </p>
<p> YOU ACKNOWLEDGE AND UNDERSTAND THAT WE DO NOT WARRANT THE SERVICE WILL BE ALWAYS ACCESSABLE, UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, THAT THE INFORMATION YOU OBTAIN FROM OTHER MEMBERS THROUGH THE SERVICE WILL BE ACCURATE OR RELIABLE, THAT THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL PURCHASED THROUGH THE WEBSITE WILL YOUR MEET EXPECTATIONS, OR THAT DEFECTS IN THE SERVICE OR ERRORS ON THE SITE WILL BE CORRECTED. WE ARE NOT RESPONSIBLE FOR ANY PROBLEMS, TECHNICAL ERRORS OR MALFUNCTION OF ANY TELEPHONE LINES, COMPUTER SYSTEMS, NETWORKS, COMPUTER EQUIPMENT, SERVERS OR PROVIDERS, HARDWARE, SOFTWARE, EMAIL CLIENT, OR MEDIA PLAYERS ON ACCOUNT OF THECNICAL PROBLEMS OR TRAFFIC CONJECTION ON THE INTERNET OR AT ANY WEBSITE OR COMBINTION THEREOF, INCLUDING DAMAGE OR INJURY TO USERS’ OR ANY OTHER PERSON’S COMPUTER RELATED TO OR RESULTING FROM PARTICIPATING OR DOWNLOADING MATERIALS IN CONNECTION WITH THE SITE OR USE OF THE SERVICE. UNDER NO CIRCUMSTANCES AND UNDER NO CAUSE OF ACTION OR LEGAL THEORY SHALL THE COMPANY OR ANY OF ITS AFFILIATES, ADVERTIZERS, PROMOTERS, DISTRIBUTION PARTNERS, SHAREHOLDERS, LICENSEES OR CONTENT PROVIDERS BE LIABLE FOR ANY LOSS OR DAMAGE, INCLUDING PERSONAL INJURY OR DEATH, RESULTING FROM ANYONE’S ACCESS TO THE WEBSITE OR USE OF THE SERVICE, ANY CONTENT ON THE SITE OR TRANSMITTED TO OUR USERS, OR RESULTING FROM ANY ONLINE OR OFFLINE INTERRACTIONS BETWEEN USERS OF THE SERVICE. </p>
<p> YOU ACKNOWLEDGE AND UNDERSTAND THAT BY TRANSMITTING ANY CONTENT THROUGH THE USE OF THE SERVICE YOU DO SO BY CHOICE AND AT YOUR OWN RISK.  YOU ARE SOLELY FOR ANY LOSS OR DAMAGES YOU INCUR IN CONNECTION WITH SUCH ACTIONS. WE ARE NOT RESONSIBLE FOR THE ACCURACY OR CORRECTNESS OF CONTENT POSTED ON OUR SITE BY OUR USERS THE ONLINE OR OFFLINE CONDUCT OF ANY USER OF THE SERVICE. WE DO NOT WARRANT THE TIMLINESS OF DELIVERY AND ASSUME NO RESPONSIBILITY FOR ANY ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, DESTRUCTION OF OR UNAUTHORIZED ACCESS TO OR NOTIFICATION OF USER COMMUNICATIONS. </p>
<p> NO INFORMATION OR ADVICE OBTAINED BY YOU IN ORAL OR WRITTEN FORM FROM OUR COMPANY, ITS AGENTS OR EMPLOYEES THROUGH OR FROM THE SERVICE WILL SUPERCEED THIS AGREEMENT OR CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS.</p>
<p><strong>LIMITATION OF LIABILITY</strong> </p>
<p> YOU ACKNOWLEDGE AND UNDERSTAND IN NO EVENT WILL SWURVE.COM BE LIABLE TO YOU FOR ANY INCIDENTAL, INDIRECT, CONSEQUENTIAL, EXEMPLARY, SPECIAL OR INDIRECT DAMAGES INCLUDING, BUT NOT LIMITED TO, DAMAGES OR LOSS OF DATA, LOSS OF PROGRAMS, COST OF PROCUREMENT OF SUBSTITUTE SERVICES OT SERVICE INTERRUPTIONS ARISING FROM USAGE OR INABILITY TO USE THE SERVICE OR ACCESS THE WEBSITE EVEN IF SWURVE.COM, ITS AGENTS OR REPRESENTATIVES KNOW OR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. YOU AGREE THAT WE WILL NOT BE HELD LIABLE FOR THE CONDUCT OF ANY USER OR OTHER THIRD PARTY ON THE SERVICE 9INCLUDING UNAUTHROIZED USERS OR “HACKERS”), THE UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR CONTENT ON THE SERVICE, OR THE ACTIONS OR INACTIONS OF USERS ON OUR SITE. </p>
<p> YOU ACKNOWLEDGE AND UNDERSTAND THE COMPANY WILL NOT BE HELD LIABLE FOR ANY FAILURE OR DELAY IN PERFORMING SERVICE WHERE SUCH FAILURE OR DELAY IS DUE TO CAUSES BEYOND THE COMPANY’S REASONABLE CONTROL, INCLUDING, BUT NOT LIMITED TO, NATURAL DISASTERS, ACTS OF TERRORISM, GOVERNMENTAL ACTS, LAWS AND REGULATIONS, LABOR STRIKES, THE BREAKDOWN OF COMMUNICATIONS SYSTEMS OR INFRASTRUCTURE, HARDWARE OR SOFTWARE FAILURES, PIRACY, OR TRANSPORTATION STOPPAGES. </p>
<p> YOU ACKNOWLEDGE AND UNDERSTAND IN ALL EVENTS SWURVE.COM’S LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO SWURVE.COM FOR THE SERVICE DURING THE TERM OF MEMBERSHIP AND THAT IN NO EVENT WILL THE COMPANY’S AGGREGATE LIABILITY TO YOU OR ANY THRID PARTY IN ANY MATTER ARRISING FROM, IN RELATION TO, OR CONNECTED WITH USE OF THE SERVICE OR THESE TERMS EXCEED THE SUM OF ONE HUNDRED DOLLARS ($100 USD).</p>
<p>Certain jurisdictions limit the applicability of warranty disclaimers and limitations of liability so the above disclaimers of warranty and liability limitations may or may not apply to you based on your state and local laws.</p>
<p><strong>INDEMNITY</strong> </p>
<p> You agree to defend Swurve.com, its shareholders, employees and agents, affiliates, service providers, and billers from any and all third party claims, liability, damages, and expenses as well as compensate all costs, including, but not limited to, reasonable attorneys fees, arising from your use (or any other user of your account) of the Service, your violation of the terms outlined in the Agreement, your provision of content to the Service, or your infringement of any intellectual property or other individual’s rights.</p>
<p><strong>GOVERNING LAW AND JURISDICTION</strong></p>
<p>You acknowledge and understand that this Agreement and all matters arising out of or otherwise relating to the Agreement and/or in connection with access to Swurve.com or use of the Service shall be governed by the laws of the State of Florida without regard to conflict of laws provisions. Any and all disputes arising out of the terms outlined in the Agreement must be, without exception, brought to court and litigated in Pinellas County, Florida. </p>
<p> You agree that:</p>
<ol type="a" class="alpha">
  <li>All actions or proceedings arising in connection with the terms and conditions of the Agreement or any services or business interactions between you and Swurve.com, its shareholders, agents or other parties that may be subject to the Agreement, shall be tried and/or litigated exclusively in the State and Federal courts located in Pinellas County, Florida</li>
  <li>Exclusive jurisdiction shall be in, and only in, Pinellas County, Florida     </li>
  <li>Exclusive venue shall be in, and only in, Pinellas County, Florida</li>
  <li>The choice of venue and forum is mandatory and not permissive in nature, thereby precluding any possibility of litigation between the parties with respect to, or arising out of, the Agreement in a jurisdiction other than that specified in this paragraph</li>
  <li>You are hereby waiving any right to assert the doctrine of forum non-conveniens or similar doctrines, or to object to venue with respect to any proceeding brought in accordance with this paragraph or with respect to any dispute under the Agreement whatsoever</li>
  <li>You are hereby stipulating that the State and Federal courts located in Pinellas County, Florida shall have personal jurisdiction over you, the company and all parties subject to the Agreement, for the purpose of litigating any dispute, controversy, or proceeding arising out of, or related to, the Agreement and/or the relationship between you and the Service </li>
  <li>You hereby authorize and accept service of process sufficient for personal jurisdiction in any legal action by registered or certified mail, Federal Express, proof of delivery or return receipt requested, to the parties address for the giving of notices as set forth in the Agreement</li>
  <li>Any final judgment rendered against a party in any action or proceeding shall be conclusive as to the subject of such final judgment and may be enforced in other jurisdictions in any manner provided by such if law enforcement becomes necessary</li>
</ol>
<p><strong>GENERAL PROVISIONS</strong> </p>
<p> This Agreement, accepted by you upon registration to Swurve.com and access to the website and Service, constitutes the entire agreement between you and Swurve Media Corporation regarding the Service and the website and shall supersede all prior and contemporaneous agreements between the parties regarding their subject matter. Your membership within the Swurve.com online community shall terminate immediately and access privileges shall be revoked without notice should you breach any of the terms and conditions outlined in the Agreement. Unless otherwise explicitly stated the Agreement will survive the termination of your account and access to the Service. The invalidity or unenforceability of any part the Agreement shall not affect the validity or enforceability of the remaining terms and conditions of the Agreement, or the Agreement as a whole, all of which shall remain in full force and effect.</p>
<p align="center">If you have any questions or concerns about the Agreement, our Company, or the Service you can contact us at <a href="mailto:support@swurve.com">support@swurve.com</a> or by sending us postal mail to: Swurve Media Corp, 1497 Main St, Suite 331, Dunedin, FL 34698 </p>