<?php if (Core::$camgirl AND Core::$camgirl->show_notice == '1'): ?>
    <div style="margin: 0 auto; width: 850px; text-align: left;">
        <h1>Notice</h1>

        <p>
            Income can only be generated by chatting with the paying male users of the community.<br />
            Any minutes accumulated through hostess to hostess chat have been removed.
        </p>

        <form method="post">
            <input type="hidden" name="action" value="confirmed" />
            <input type="submit" value="Continue" name="submit" />
        </form>
    </div>
<?php return; endif; ?>

<?php if (Core::$camgirl AND Core::$camgirl->account == 'manager'): ?>
    <?php $hostesses = ORM::factory('camgirl')->where('referral_id', '=', Core::$camgirl->id)->find_all(); ?>

    <?php if (Core::$camgirl->have_w9 == 'No' AND Core::$camgirl->country_id == 233): ?>
    <div class="alert" style="padding-top: 20px; padding-bottom: 0;">We have not recieved your W-9.  A completed W-9 form is required for all US affiliates.  <?= HTML::anchor('/account/support/w9', 'Click Here'); ?> for details.</div><br />
    <?php endif; ?>

    <div style="margin: 0 auto; width: 850px; text-align: center;">
        <h1>Pay Period: <?= date('m-d-Y', $range->start); ?> to <?= date('m-d-Y', $range->end); ?></h1><br />

        <?php if ($hostesses->count() == 0): ?>
        <p>You have no referrals, use the link below to refer new hostesses!</p>
        <div style="width: 275px; border: 2px solid #ccc; background-color: #fff; padding: 5px; display: inline-block;">http://flirtbucks.net/?r=<?= Core::$camgirl->id; ?></div>
        <?php else: ?>
        <?php
        //Core::$camgirl->pending_commission
            $total = 0;

            foreach($hostesses as $hostess)
            {
                $stats = ORM::factory('chat_tracker')->get_stats_daterange($hostess, $range);

        ?>
            <div style="margin: 0 auto; font-size: 16px; font-weight: bold; width: 800px; line-height: 20px;">
                <div style="width: 100%; font-size: 16px; padding: 3px; text-align: center; text-decoration: underline;"><?= $hostess->first_name; ?> <?= $hostess->last_name; ?> Stats</div>
                <?php if (count($stats) == 0): ?>
                <div style="width: 100%; font-size: 14px; padding: 3px; text-align: center;">No earnings this period.</div>
                <?php else: ?>
                <div style="float: left; width: 150px; font-size: 16px; padding: 3px; text-align: center;">&nbsp;</div>
                <div style="float: left; width: 150px; font-size: 16px; padding: 3px; text-align: center; font-weight: bold;">Credits</div>
                <div style="float: left; width: 150px; font-size: 16px; padding: 3px; text-align: center; font-weight: bold;">Rate</div>
                <div style="float: left; width: 150px; font-size: 16px; padding: 3px; text-align: center; font-weight: bold;">Comission</div>
                <div style="float: left; width: 150px; font-size: 16px; padding: 3px; text-align: center; font-weight: bold;">Your Share</div>
                <?php endif; ?>
            </div>
        <?php

                $count = 0; foreach($stats as $stat): $stat->tier = $stat->tier ? $stat->tier : $hostess->tier; ?>
            <div style="margin: 0 auto;  font-size: 16px; font-weight: bold; width: 800px; line-height: 20px;">
                <div style="float: left; width: 150px; font-size: 16px; padding: 3px; text-align: center;"><?= $stat->type; ?> Chat</div>

                <?php if ($count == 0): ?>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;"><?= $stat->pcount; ?></div>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;"><?= number_format($GLOBALS['tiers'][$stat->tier][$stat->type], 2); ?>&cent;</div>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;">$<?= number_format($stat->pcount / ($stat->type == 'Text' ? 1 : 3) * $GLOBALS['tiers'][$stat->tier][$stat->type], 2); ?></div>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;">$<?= number_format($stat->pcount / ($stat->type == 'Text' ? 1 : 3) * ($GLOBALS['tiers'][3][$stat->type] - $GLOBALS['tiers'][$stat->tier][$stat->type]), 2); ?></div>
                <?php else: ?>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border-left: 1px solid #95999C; border-bottom: 1px solid #95999C; border-right: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;"><?= $stat->pcount; ?></div>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border-left: 1px solid #95999C; border-bottom: 1px solid #95999C; border-right: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;"><?= number_format($GLOBALS['tiers'][$stat->tier][$stat->type], 2); ?>&cent;</div>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border-left: 1px solid #95999C; border-bottom: 1px solid #95999C; border-right: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;">$<?= number_format($stat->pcount / ($stat->type == 'Text' ? 1 : 3) * $GLOBALS['tiers'][$stat->tier][$stat->type], 2); ?></div>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border-left: 1px solid #95999C; border-bottom: 1px solid #95999C; border-right: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;">$<?= number_format($stat->pcount / ($stat->type == 'Text' ? 1 : 3) * ($GLOBALS['tiers'][3][$stat->type] - $GLOBALS['tiers'][$stat->tier][$stat->type]), 2); ?></div>
                <?php endif; ?>
            </div>
            <?php $total += $stat->pcount / ($stat->type == 'Text' ? 1 : 3) * ($GLOBALS['tiers'][3][$stat->type] - $GLOBALS['tiers'][$stat->tier][$stat->type]); $count++; endforeach;
                echo '<br />';
            }
        ?>
        <h2 style="clear: both;"><br />Pending Total Payout: $<?= number_format(Core::$camgirl->pending_commission + $total, 2); ?></h2>
        <?php endif; ?>
    </div>
<?php elseif (Core::$camgirl AND Core::$camgirl->status == 'Pending'): ?>
    <h1 style="text-align: left;">Your Account is Pending Approval</h1>
    <p>Thank you for applying, to finish your application process please send an email to <?= HTML::mailto('support@flirtbucks.net'); ?> with an attached image of a state issued photo id.</p>
    <p>These instructions have been emailed to you, feel free to reply to that email with the required information to validate your account.</p>
<?php elseif (Core::$camgirl AND Core::$camgirl->status == 'Approved'): ?>
    <?php if (Core::$camgirl->have_w9 == 'No' AND Core::$camgirl->country_id == 233): ?>
    <div class="alert" style="padding-top: 20px; padding-bottom: 0;">We have not recieved your W-9.  A completed W-9 form is required for all US affiliates.  <?= HTML::anchor('/account/support/w9', 'Click Here'); ?> for details.</div><br />
    <?php endif; ?>

    <div style="margin: 0 auto; width: 700px; text-align: center;">
        <h1>Pay Period: <?= date('m-d-Y', $range->start); ?> to <?= date('m-d-Y', $range->end); ?> (Tier <?= $tier; ?>)</h1><br />

        <div style="margin-left: -20px;">
            <?php if (count($stats)): ?>
            <div style="margin: 0 auto; font-size: 16px; font-weight: bold; width: 630px; line-height: 20px;">
                <div style="float: left; width: 150px; font-size: 16px; padding: 3px; text-align: center;">&nbsp;</div>
                <div style="float: left; width: 150px; font-size: 16px; padding: 3px; text-align: center; font-weight: bold;">Credits</div>
                <div style="float: left; width: 150px; font-size: 16px; padding: 3px; text-align: center; font-weight: bold;">Rate</div>
                <div style="float: left; width: 150px; font-size: 16px; padding: 3px; text-align: center; font-weight: bold;">Comission</div>
            </div>
            <?php else: ?>
            <div style="margin: 0 auto; font-size: 16px; font-weight: bold; width: 630px; line-height: 20px;">
                <h3>Click connect below and start earning comission now.</h3>
            </div>
            <?php endif; ?>

            <?php $total = 0; $count = 0; foreach($stats as $stat): $stat->tier = $stat->tier ? $stat->tier : $tier; ?>
            <div style="margin: 0 auto;  font-size: 16px; font-weight: bold; width: 630px; line-height: 20px;">
                <div style="float: left; width: 150px; font-size: 16px; padding: 3px; text-align: center;"><?= $stat->type; ?> Chat</div>

                <?php if ($count == 0): ?>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;"><?= $stat->pcount; ?></div>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;"><?= number_format($GLOBALS['tiers'][$stat->tier][$stat->type], 2); ?>&cent;</div>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;">$<?= number_format($stat->pcount / ($stat->type == 'Text' ? 1 : 3) * $GLOBALS['tiers'][$stat->tier][$stat->type], 2); ?></div>
                <?php else: ?>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border-left: 1px solid #95999C; border-bottom: 1px solid #95999C; border-right: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;"><?= $stat->pcount; ?></div>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border-left: 1px solid #95999C; border-bottom: 1px solid #95999C; border-right: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;"><?= number_format($GLOBALS['tiers'][$stat->tier][$stat->type], 2); ?>&cent;</div>
                <div style="float: left; width: 150px; background-color: #FFFDFB; border-left: 1px solid #95999C; border-bottom: 1px solid #95999C; border-right: 1px solid #95999C; color: #000; font-size: 14px; padding: 3px; text-align: center;">$<?= number_format($stat->pcount / ($stat->type == 'Text' ? 1 : 3) * $GLOBALS['tiers'][$stat->tier][$stat->type], 2); ?></div>
                <?php endif; ?>
            </div>
            <?php $total += $stat->pcount / ($stat->type == 'Text' ? 1 : 3) * $GLOBALS['tiers'][$stat->tier][$stat->type]; $count++; endforeach; ?>
        </div>

        <div class="clear"></div><br /><br />

        <h2>Pending Total Payout: $<?= number_format(Core::$camgirl->pending_commission + $total, 2); ?></h2>

        <center><?= HTML::anchor('https://www.swurve.com/auto/login/user/online?' . Core::$camgirl->swurve->username . '/' . Core::$camgirl->swurve->password, HTML::image('assets/img/flirtbucks/connect.png', array('style' => '')), NULL, 'https'); ?></center>
    </div><br />
<?php else: ?>
    <h1 style="text-align: left; margin-left: 20px;">Ever Wish You Could Get PAID to Chat?</h1>

    <div class="left-promo">
        <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="318" height="180" id="swurve-flash">
            <param name="movie" value="/assets/img/flirtbucks/flirt.swf" />
            <!--[if !IE]>-->
            <object type="application/x-shockwave-flash" data="/assets/img/flirtbucks/flirt.swf" width="318" height="180">
            <!--<![endif]-->
                <a href="http://www.adobe.com/go/getflashplayer">
                    <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" />
                </a>
            <!--[if !IE]>-->
            </object>
            <!--<![endif]-->
        </object>
    </div>

    <div class="right-promo" style="margin-top: 12px;">
        <p>Do you have an engaging personality and love to talk with new and interesting people? Do you love to spend time on social networking and online community sites? Do you desire to earn a great income through a fun and easy job right from the comfort of your own home?</p>
        <p>If you answered "yes" to the questions above then we’ve got the job for you! At FlirtBucks we’re looking for Chat Hostesses - motivated women who enjoy chatting and socializing online and are looking to earn big bucks. That’s right! Earn real money getting paid to do someting you enjoy!</p>
    </div>

    <div class="clear"></div><br />

    <h1 style="text-align: left; margin-left: 20px;">We Pay You to Chat, not “Perform”</h1>
    <p style="margin-left: 20px;">FlirtBucks is not a cam performer, psychic line or phone actress program. You don’t have to pretend to be someone else, take orders from anyone and no nudity is required. As a chat hostess we encourage you to be yourself. Unlike other programs FlirtBucks puts YOU in control. You only chat with users YOU want to chat with and talk about the things YOU want to discuss. If you can multitask, have good conversation skills and a great personality you too can make great money working from your own home.</p>

    <h1 style="text-align: left; margin-left: 20px;">Think You’ve Got What It Takes?</h1>
    <?= HTML::image('assets/img/flirtbucks/money.png', array('style' => 'float: right; text-align: right; padding-left: 20px;')); ?>
    <p style="margin-left: 20px;">
        If you’re a woman at least 18 years of age or older and have access to a computer equiped with a webcam and a high speed connection you have all the tools you need to get started. No hardware or software to buy, no application fees.  With FlirtBucks you work the hours you choose- morning, noon, or the middle of the night- for as long or as little as you want.  So what are you waiting for? Are you ready to start earning more money?
        <br /><center><?= HTML::anchor('/account/create', HTML::image('assets/img/flirtbucks/button-apply.png'), array('style' => 'background-color: #FBF7EE;')); ?></center>
    </p>

    <div class="clear"></div>
<?php endif; ?>