<style> 
    ol.alpha {
        list-style-type: lower-alpha;
        padding-left: 50px;
        padding-bottom: 20px;
    }
     
    ol.num {
        list-style-type: decimal;
        padding-left: 50px;
        padding-bottom: 20px;
    }

    li {
        color: #D4106A;
    }
     
    p strong {
        color: #D4106A;
    }
</style>

<h1>FlirtBucks Privacy Policy</h1>
<p>This Privacy Policy (“the Policy”) is offered as a service to inform users of the Flirtbucks.net website and Program how we collect, categorize, and disclose the personal information you provide to us and content you upload through use of the Program. We reserve the right, at our sole discretion, to alter the Policy at any time. Any changes made will be considered effective immediately upon notice. Notice of changes to the Policy will be posted on the site whenever significant updates are made. Your continued use of the Service after such notice signifies your acceptance of these changes. A link to the Policy will always be made available to you through inclusion in the footer located on the bottom of the Service’s home page for your review at any time. </p>
<p>Flirtbucks.net is created for, and intended to be accessed exclusively by, ADULTS ONLY. Access or use of this website in any way by individuals under the age of 18 years old is strictly prohibited. As a community which expressly and strictly limits its membership to adults 18 years of age and older we do not knowingly seek or collect and personal information or data from individuals who we find do not meet this criteria.</p>
<p>By registering an account with Flirtbucks.net, and by your continued access to the Program, you consent to the collection, use and disclosure of your information as outlined in this Policy.</p>

<p><strong>TYPES OF DATA</strong></p>
<p>We categorize the data we collect as either Personally Identifiable Information (“Personal Data”) or Aggregate and Anonymous Information (“AA Data”).</p>
<p>Personal Data is any information that can be used to identify a specific individual, such as your name, email address, home address, and phone number. AA Data is information collected automatically through the use and operation of the Site and does not disclose any personally revealing information about you. </p>

<p><strong>INFORMATION COLLECTED AUTOMATICALLY</strong></p>
<p>Each time an individual accesses Flirtbucks.net our servers log various pieces of AA Data valuable to us for the operation of the website. The data we collect includes, but is not limited to, the referring URL, the visitors IP address, and the browser type and software version the visitor is using to view and interact with the Program. We also log the succession or order and frequency a user views pages on the website (Clickstream Data). This is done to help us define traffic patterns or “flow” and the data collected and stored in these logs does not contain any Personal Data or link back in any way to a user’s individual account. Collecting this data helps us understand where the traffic to our site is coming from and allows us to better tailor the navigation, features and functionality of the site to provide you with a better overall user experience.  </p>
<p>We also employ the use of cookies. A cookie is a small data file that works with your browser to not only help us track inbound traffic sources and referrals but also helps us manage your feature access. For example, a cookie is what remembers you have logged in successfully and grants you access to members only or premium features of the site according to your current membership level without forcing you, the user, to log in upon every page load or action. You can set your browser to block cookies, but understand that doing so will seriously hinder your overall member experience and may make features of the Program inaccessible. </p>
<p>From time to time we may choose to merge information about visitors with the Service’s traffic data to gain perspective of the service’s performance with various demographics. We may choose to share this aggregated data with our advertisers and publishing partners. This group data and our Service statistics in no way disclose your individual identity or disclose any personally identifiable information of any of our users to third parties. </p>
<p>None of the information we collect automatically is classified as Personal Data. Your IP address (the series of numbers associated with your individual computer issued by your ISP) does not disclose any personally revealing information about you. When we log automatically gathered data we do not link your IP address to any of your Personal Data we store in conjunction with your user record, and is stored separately on our servers, which means your session is logged anonymously. Your IP address would only be used to identify you in compliance with your ISP in cases of necessity, such as, but not limited to,  where our Terms of Service had been violated or to investigations involving abuse, harassment, identity theft, fraud, malicious intent or compromised financial information.</p>

<p><strong>INFORMATION COLLECTED FOR REGISTRATION</strong></p>
<p>We encourage all users of FlirtBucks to completely fill out all fields of their profile to achieve an optimum user experience. The additional information you provide not only helps users of the service learn more about you, but it also expands the amount of searchable and matchable data in the system, increasing your profile’s exposure to other members of the service and generating more targeted user interest in your account.</p>
<p>During the registration process we will ask you for both general and personal information for the purpose of providing you with a customized service. Your date of birth, while never shared with other members, is a service requirement when registering your account as we are an age restricted community and age is a barrier to entry. Your gender is also applicable as it not only relates to what members you are presented with as possible matches and are viewable by you through the Service, but also is a necessity in determining what members will also be able to search, browse, match with and view your profile. </p>
<p>As you create your account you will be given the opportunity to create a pseudonymous profile including a username which will act as your personal unique identifier within the community. You may include your first name at your own discretion but usernames that include a surname will be edited or removed. A valid personal email address is also a requirement for registration. Your personal contact details such as your email address (and your phone number if you chose to receive SMS notifications) will remain private and will not be shared with any third parties or other users of the Service.</p>

<p><strong>USAGE OF PERSONAL DATA</strong></p>
<p>Your email address and other Personal Data you share directly with Flirtbucks.net when creating and maintaining your user account is not shared with any third parties and is solely used internally in the provision of our member services to you. We retain user records and Personal Data only for so long as required to fulfill the purpose for which it was collected or as required to by law. Your email address and other contact information will only be used in conjunction with our service, sending you vital communications such as, but not limited to, your account details, website updates, receipts of electronic payments, communication notifications and other important service announcements that affect your membership with FlirtBucks.net. </p>
<p>Should you choose to become a premium member of our service via an electronic payment method, Personal Data will be requested of you to process your payment. This data is shared with a trusted third party payment processor so they may process your payment. While the information submitted to our payment processor is not governed by this Policy, we do require that these entities not use your information for any purpose not in connection with the billing and account management of our Service.</p>

<p><strong>VOLUNTARY PUBLICATION OF PERSONAL DATA</strong></p>
<p>Any personally identifiable information that you broadcast through the service you do at your own discretion. You agree to hold FlirtBucks.net and its parent company harmless for any privacy issues that may arise from your use of the service and your choice of personal information you choose to share with others via the Service. Personal data that you include in the content of your profile, communications with other users such as email and text chat, or through digital media such as photographs, videos and streaming live cam is voluntarily done at your own risk and you agree that you, and not the company, its affiliates, partners and content providers, are solely responsible and liable for any damages and/or consequences that arise from your willful publication of personally identifiable information through the Service.</p>

<p><strong>EMPLOYEE ACCESS TO INFORMATION</strong></p>
<p>Access to Personal Data is limited to authorized employees whose duties in accordance with the day to day operation of the Service provide them with a legitimate business reason to do so. As a condition of employment all employees of FlirtBucks.net are subject to a strictly enforced Non-Disclosure Agreement in accordance with this Policy. Disclosure of, or unauthorized access to, Personal Data by an employee of the company is strictly prohibited. Failure to uphold the standards for non-disclosure outlined in the Policy and/ or violation of the Non-Disclosure Agreement by employees of FlirtBucks.net will result in disciplinary action, up to and including termination.</p>

<p><strong>INFORMATION COLLECTED BY THIRD PARTIES</strong></p>
<p>Throughout the Service we may present links to on our website or through email communications from the Service that direct to products or services that are served by websites owned and operated by third parties. Some of these may be partnership promotions which offer a product or service at a special rate, discount, or contain an additional premium for members of our community, and these sites may contain our brand name, trademarks, and display other intellectual property we own in accordance with the offer. Regardless of the presence of our branding it is important that you understand that once you have transferred to a third party’s website or service we do not control the information they collect and any Personal Data you submit to these third parties shall not be controlled by this Policy. We strongly encourage you to familiarize yourself with the privacy policies of these third party websites as we do not warranty their internal operations and are not liable for their actions or omissions.</p>

<p><strong>COOPERATION WITH LAW ENFORCEMENT AGENCIES</strong></p>
<p>As outlined in the <a href="/terms">Terms of Service</a> Agreement, FlirtBucks.net reserves the right to fully comply with any and all law enforcement agencies and court orders requesting or directing the company, its affiliates and content providers to disclose information, including Personal Data, regarding any individual who is using or has used the Service or has obtained content available or in association with the website. </p>
<p>If you have any questions or concerns about the Policy, our company, or the Service, you can contact us at <a href="mailto:support@flirtbucks.net">support@flirtbucks.net</a> or by sending us postal mail to:FlirtBucks, 1497 Main St, Suite 331, Dunedin, FL 34698 </p>